--ANALYTICAL FUNCTIONS--
--FOLLOWING IS NORMAL GROUPING QUERY
SELECT  DEPARTMENT_ID, COUNT(DEPARTMENT_ID) EMPLOYEES FROM EMPLOYEES WHERE DEPARTMENT_ID IN(10,20,30,40)
GROUP BY DEPARTMENT_ID;

--FOLLOWING USING ANALYTICAL FUCTNION PRATITION

SELECT EMPLOYEE_ID,DEPARTMENT_ID, COUNT(*) OVER(PARTITION BY DEPARTMENT_ID) DEPARTMENT_COUNT FROM EMPLOYEES
WHERE DEPARTMENT_ID IN(10,20,30,40);

--ROW_NUMBER()

SELECT EMPLOYEE_ID,DEPARTMENT_ID,HIRE_DATE,ROW_NUMBER()OVER(PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE) SNO 
FROM EMPLOYEES WHERE  DEPARTMENT_ID IN(10,30) ORDER BY DEPARTMENT_ID, SNO;

--RANK

SELECT  SALARY,EMPLOYEE_ID FROM (SELECT EMPLOYEE_ID,SALARY,DENSE_RANK() OVER (ORDER BY SALARY DESC) AS RANK FROM EMPLOYEES )
WHERE RANK<=4;




