-- test_queries --

--EMPS WORKING FOR THE PAST FIVE YEARS

SELECT EMPLOYEE_ID, FIRST_NAME,HIRE_DATE FROM EMPLOYEES WHERE EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM HIRE_DATE)>=5;

--EMPS JOINED BEFORE 30-06-1990 OR AFTER 31-DEC-1990

SELECT EMPLOYEE_ID,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE < '30-JUN-1990'
UNION 
SELECT EMPLOYEE_ID,HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE > '31-DEC-1990'
ORDER BY HIRE_DATE;

SELECT FIRST_NAME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE 'S%';

SELECT FIRST_NAME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE '_A%';

SELECT FIRST_NAME FROM EMPLOYEES WHERE LENGTH(FIRST_NAME)=5;

--NO OF EMPS IN EACH JOB

SELECT JOB_ID,COUNT(*) NO_OF_EMPLOYEES FROM EMPLOYEES GROUP BY JOB_ID; 

SELECT DEPARTMENT_ID,SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID ORDER BY DEPARTMENT_ID;

--DEPTS WITH MORE THAN THREE EMPS

SELECT DEPARTMENT_ID,DEP_COUNT FROM
(SELECT DEPARTMENT_ID,COUNT(*) DEP_COUNT FROM EMPLOYEES GROUP BY DEPARTMENT_ID)
WHERE DEP_COUNT>30;

SELECT JOB_ID,TOTAL_SALARY FROM(SELECT JOB_ID,SUM(SALARY) TOTAL_SALARY FROM EMPLOYEES GROUP BY JOB_ID )
WHERE TOTAL_SALARY>20000;

--Nth highest salary

SELECT EMPLOYEE_ID,SALARY FROM (SELECT EMPLOYEE_ID,SALARY, DENSE_RANK() OVER(ORDER BY SALARY DESC) RANK FROM EMPLOYEES)
WHERE RANK=1;

--Nth lowest salary

SELECT EMPLOYEE_ID,SALARY FROM (SELECT EMPLOYEE_ID,SALARY,DENSE_RANK() OVER(ORDER BY SALARY ASC) RANK FROM EMPLOYEES)
WHERE RANK=3;

-- NO OF EMPS GETTING HIGEST SALARY

SELECT COUNT(*) FROM (
SELECT EMPLOYEE_ID,SALARY FROM (SELECT EMPLOYEE_ID,SALARY, DENSE_RANK() OVER(ORDER BY SALARY DESC) RANK FROM EMPLOYEES)
WHERE RANK=1
);




